### ISSUE TITLE
Wrong sentence in collection description

### ISSUE THREAD

**Issue by KevCui** [postmanlabs/covid-19-apis#100]
There is a wrong sentence in collection description on the doc page 
https://documenter.getpostman.com/view/8854915/SzS7NkEt?version=latest 
and
https://documenter.getpostman.com/view/8854915/SzS7NkKA?version=latest

```
Before you can use, you will have to setup your own [Twitter application and configure Postman before you can use](https://community.postman.com/t/twitter-api-authorization/9512.
```

2 small things:
1. The 2nd `before you can use` is redundant.
2. The ")" character is missing after URL link, which causes the broken markdown formatting.

**Comment by kinlane** [comment]
Thanks for helping us improve the quality of our collections. This collection has just been updated to use the new Twitter Recent Search API (V2) from labs, so the language has all been updated.
