### ISSUE TITLE
Link of "Website scraping to API" misdirects to Sheets to API page in README

### ISSUE THREAD

**Issue by ProBeta1** [postmanlabs/covid-19-apis#101]
And the docs are just empty , would any general information be provided there ?

**Comment by kinlane** [comment]
Just tested on landing page (https://covid-19-apis.postman.com/) and it goes to proper page w/ content. unable to verify. Can you provide more context?

**Comment by ProBeta1** [comment]
@kinlane It is occuring in README file .
