### ISSUE TITLE
API that serves the live patient database for COVID19 cases in India

### ISSUE THREAD

**Issue by sudevschiz** [postmanlabs/covid-19-apis#104]
covid19india.org is a crowdsourced volunteer initiative which is collecting and curating the patients level details as soon as verified information is available. Also, the volunteers are making the connection between the patients to identify cluster formation.

All the data is publicly available through https://api.covid19india.org

**Comment by ProBeta1** [comment]
It can be assigned to me.

**Comment by kinlane** [comment]
Thanks for submitting. I am adding it to our list of projects to create Postman collections for. Once it has a collection we can add to the list of COVID-19 APIs.

**Comment by ProBeta1** [comment]
@kinlane Have a look : [Collection](https://documenter.getpostman.com/view/10724784/SzYXXKmA?version=latest)

**Comment by kinlane** [comment]
Nice. Looks good. Tagging for inclusion.

**Comment by ProBeta1** [comment]
https://github.com/postmanlabs/covid-19-apis/pull/119

**Comment by kinlane** [comment]
Ok this has been included in #122 and upon review it will be merged.
