### ISSUE TITLE
Covid India State-wise Data 

### ISSUE THREAD

**Issue by udaya2899** [postmanlabs/covid-19-apis#105]
I'd like to submit this API [covid-india-api](https://github.com/udaya2899/covid-india-api). It scraps data from https:mohfw.gov.in (Official Website of Ministry of Health and Family Welfare, Govt. of India) and serializes it as JSON and exposed as a GET REST API. The API is also well documented and is maintained by me.

The application is hosted for use at https://covid-india-api.herokuapp.com/api
Kindly verify and let me know if this could be added to the Covid-19 Postman collection

**Comment by ProBeta1** [comment]
Nice job @udaya2899 . The project collaborators would check it soon. Meanwhile you may add more API routes if possible.

**Comment by udaya2899** [comment]
As mentioned by @kinlane in #75 , I have created a Postman Collection and properly documented the API Requests. 

[covid-india-api Postman Collection Documentation](https://documenter.getpostman.com/view/5310017/SzYW4LYY) is the link for the Collection Documentation

**Comment by volumetric** [comment]
Amazing work @udaya2899

**Comment by kinlane** [comment]
Hello there! Thanks for your submission. Yes, we can add your API to our list, but first we'll need to create a Postman collection for it. I am adding it to the queue of APIs to create collections for and the Postman team or the community will tackle--once the Postman collection is posted here we can add to the list.

**Comment by ProBeta1** [comment]
@kinlane Collection is already created [link](https://documenter.getpostman.com/view/5310017/SzYW4LYY?version=latest) by him

**Comment by kinlane** [comment]
Sorry I missed. Not sure why I didn't see it. Adding to list to add.

**Comment by udaya2899** [comment]
Hello @kinlane , as mentioned by @ProBeta1 the collection has been created and I'm putting the link once again here for your reference 

**### https://documenter.getpostman.com/view/5310017/SzYW4LYY?version=latest**

**Comment by ProBeta1** [comment]
https://github.com/postmanlabs/covid-19-apis/pull/119

**Comment by kinlane** [comment]
Ok this has been included in #122 and upon review it will be merged.
