### ISSUE TITLE
API Suggestion: API based on Johns Hopkins CSSE data

### ISSUE THREAD

**Issue by elitemaks** [postmanlabs/covid-19-apis#111]
Hi, I'd like to suggest the API developed by our team. It's based on public data provided by Johns Hopkins CSSE. Website - https://covid-api.com/

**Comment by ProBeta1** [comment]
Is it just me who is unable to access the Documentation redirection ?

**Comment by elitemaks** [comment]
@ProBeta1 thanks for noticing, fixed.

**Comment by ProBeta1** [comment]
Thanks for fixing , would add your API soon :)

**Comment by ProBeta1** [comment]
Postman Collection : [Link](https://documenter.getpostman.com/view/10724784/SzYXWz3x?version=latest)

**Comment by kinlane** [comment]
Thanks for the collection -- queuing it up for adding to our list. Thanks.

**Comment by ProBeta1** [comment]
https://github.com/postmanlabs/covid-19-apis/pull/119

**Comment by kinlane** [comment]
Ok this has been included in #122 and upon review it will be merged.

**Comment by elitemaks** [comment]
@ProBeta1 hi, I checked the doc, and it seems like there Is missing base URL. All requests are listed like /regions, but user cannot see the full request URL with base URL.

**Comment by elitemaks** [comment]
@ProBeta1 also, there is an error in the response format for /reports  - we do not provide multiple regions in one call.  It should be 
`report => {
  "region": {
     "cities": []
  }
},`

instead of 

`report => {
  "region": [
    {
       "cities": []
    },
    {
       "cities": []
    }
  ]
},`

**Comment by ProBeta1** [comment]
@elitemaks Thanks for noticing . I generated the collection directly using Import . I'll check the issue.

**Comment by ProBeta1** [comment]
@elitemaks Have a look now :blush:

**Comment by elitemaks** [comment]
@ProBeta1 thanks for fixing and thank you for noticing too! Fixed.

**Comment by elitemaks** [comment]
@ProBeta1 Hi, we added a new endpoint, /reports/total, here is an example - https://covid-api.com/api/reports/total?date=2020-04-07

Please let me know, what is the correct way of submitting changes to the documentation here.

**Comment by ProBeta1** [comment]
Okay , I will add it .

**Comment by ProBeta1** [comment]
@elitemaks Added :)

**Comment by elitemaks** [comment]
@ProBeta1 thank you, but is there a way I can edit documentation myself? We evolve this API and I need to reflect changes in the doc. Please advise.

**Comment by ProBeta1** [comment]
Yeah @elitemaks , indeed there is . 
You need to fork the collection in your Postman App locally and then make the desired changes . When done , you may create a pull request , which would then be merged in the original collection.
