### ISSUE TITLE
Request to Add My API into API Collections

### ISSUE THREAD

**Issue by HrithikMittal** [postmanlabs/covid-19-apis#113]
I created the APIs to get the details of COVID - 19 in Indian states. It will give an accurate count of confirmed cases, as well as state-wise analysis also. The data is used from the official website of the Ministry of Health and Family Welfare of India.

These API’s can be used for an Application. I used real-time updation of the database with the help of AWS action which triggered the composite end-to-end workflow and pushed it into Database for which I used Mlab.

APIs: https://covid19-india-adhikansh.herokuapp.com/
Docs: https://hrithikmittal.github.io/COVID19-India-API/

**Comment by kinlane** [comment]
Thanks so much! Adding to our work queue.  The API will need a Postman collection to be created for it to be added to the list. Once in our queue the Postman team or the community will invest time to create the collection and add here, then we'll take the unique ID of the collection and add to the list.

**Comment by HrithikMittal** [comment]
Thanks a lot! I created the collection by myself
link: https://documenter.getpostman.com/view/5665978/SzYXXedf
Please now add it to the list. Thanks

**Comment by HrithikMittal** [comment]
If anything else is required please let me know.

**Comment by ProBeta1** [comment]
https://github.com/postmanlabs/covid-19-apis/pull/119

**Comment by kinlane** [comment]
Ok this has been included in #122 and upon review it will be merged.
