### ISSUE TITLE
Feature flag to filter 3 featured sites

### ISSUE THREAD

**Issue by ch264** [postmanlabs/covid-19-apis#132]

**Comment by ch264** [comment]
Kin is adding feature flag to sites

**Comment by kinlane** [comment]
All these (an future ones) have a feature and updated property:

- California - https://covid-19-testing.github.io/locations/california/complete.json
- Washington - https://covid-19-testing.github.io/locations/washington/complete.json
- New York - https://covid-19-testing.github.io/locations/new-york/complete.json
- Massachusetts - https://covid-19-testing.github.io/locations/massachusetts/complete.json
- Florida - https://covid-19-testing.github.io/locations/florida/complete.json
- Texas - https://covid-19-testing.github.io/locations/texas/complete.json
- New Jersey - https://covid-19-testing.github.io/locations/new-jersey/complete.json
- Delaware - https://covid-19-testing.github.io/locations/delaware/complete.json
- Nevada - https://covid-19-testing.github.io/locations/nevada/complete.json
