### ISSUE TITLE
Testing Location site segment of the Resource Center landing page

### ISSUE THREAD

**Issue by hannaheneil** [postmanlabs/covid-19-apis#183]
Hi Christina,

For the section of the Resource Center that links to the Testing Location site, here is some copy:

Header: COVID-19 Testing Locations
Text: A crowdsourced list of COVID-19 testing locations across the 50 US states–to centralize the availability of up-to-date information.
CTA: See Locations

**Comment by hannaheneil** [comment]
Hi @ch264 ! Thank you!

**Comment by hannaheneil** [comment]
Whoops.

**Comment by ch264** [comment]
PR is in
