### ISSUE TITLE
Collection Dont Have Base Url's

### ISSUE THREAD

**Issue by rajattechnicallibrary** [postmanlabs/covid-19-apis#198]
Please Base Url in so many APIs

**Comment by kinlane** [comment]
We need more detail on specific collection so we can either fix if they are within our control or reach out to the owner to fix. 

Also are you looking for associated environment?

**Comment by rajattechnicallibrary** [comment]
Yes i am looking for associated environment

**Comment by kinlane** [comment]
If it is for a specific collection, I will need the URL of that collection to let you know:

1) If there is a environment or not
2) Create an environment for it.
3) Ask owner of collection to create an environment for it.
