### ISSUE TITLE
Covid-19 Nigeria API

### ISSUE THREAD

**Issue by sink-opuba** [postmanlabs/covid-19-apis#199]
Scr-API that shows covid-19 data in Nigeria by states from the NCDC

**Comment by kinlane** [comment]
Here is one possible link: https://www.ncdc.gov.ng/diseases/sitreps/?cat=14&name=An%20update%20of%20COVID-19%20outbreak%20in%20Nigeria but they are PDFs which makes it more challenging.

**Comment by sink-opuba** [comment]
Yeah I am aware of this. The API is actually scraped from the daily updates from their official website dedicated to covid19. http://covid.ncdc.gov.ng

**Comment by sink-opuba** [comment]
Yeah I am aware of this. The API is actually scraped from the daily updates from their official website dedicated to covid19. http://covid.ncdc.gov.ng

**Comment by arlemi** [comment]
@sink-opuba http://covid.ncdc.gov.ng doesn't resolve to anything for me. Can you share a bit more info here?

**Comment by sink-opuba** [comment]
@arlemi so sorry the URL is incorrect. Here is the correct one http://covid19.ncdc.gov.ng/. It's the official site that reports covid19 cases in Nigeria. No official API available yet, hence this https://covidnigeria.herokuapp.com/api. The data was scrapped from the official site.

**Comment by arlemi** [comment]
No worries and thanks for your reply @sink-opuba ! I'll create this one tomorrow and hopefully we can get it added on the next push. :) 

@kinlane Can you assign to me please? 🙏

**Comment by arlemi** [comment]
Collection is here: https://documenter.getpostman.com/view/9215231/Szf549gB?version=latest

**Comment by Shaaji4u** [comment]
@arlemi  The data in States "Lagos" seems to fall out of other current confirmedCases = 1,006,  API report = 1
casesOnAdmission = 753, API report = 6
Please look into it.

**Comment by sink-opuba** [comment]
Thanks @Shaaji4u for pointing it out. The issue has been resolved.

**Comment by arlemi** [comment]
This is now available on the API list: https://covid-19-apis.postman.com/
