### ISSUE TITLE
Drugs API

### ISSUE THREAD

**Issue by kinlane** [postmanlabs/covid-19-apis#205]
From email:

 We have developed an open web service to identify drugs mentioned in a text and classify them according to the Anatomical Therapeutic Chemical (ATC) classification system and the Concept Unique Identifiers (CUI) described in the Unified Medical Language System (UMLS). 

 The service is available here: https://librairy.linkeddata.es/bio-nlp

 It only supports POST requests to /drugs with the text to be analyzed. For example:
 
 curl -d '{"text":"however, clinical trials investigating the efficacy of several agents, including cefatrizine and chloroquine, are underway in China"}' -H "Content-Type: application/json" -X POST https://librairy.linkeddata.es/bio-nlp/drugs

And the response received is:

[{
	"name": "chloroquine",
	"atc_code": "P01BA01",
	"atc_parent": "P01BA",
	"cui": "C0008269",
	"level": 5
}, {
	"name": "cefatrizine",
	"atc_code": "J01DB07",
	"atc_parent": "J01DB",
	"cui": "C0007545",
	"level": 5
}]

 It has a web interface: https://librairy.github.io/bio-nlp/ , and the source code and usage information are available at: https://github.com/librairy/bio-nlp

 We hope it can be useful, thank you very much for the initiative.

Tasks:

- Create Postman Collection
- Add to the list

**Comment by arlemi** [comment]
@kinlane Created a Postman collection for this one here https://documenter.getpostman.com/view/9215231/Szf25VvG?version=latest

**Comment by kinlane** [comment]
You rock! Adding to the list for inclusion.

**Comment by kinlane** [comment]
Alright, this is in the queue for https://github.com/postmanlabs/covid-19-apis/pull/259.
