### ISSUE TITLE
Add Coronatracker API

### ISSUE THREAD

**Issue by kinlane** [postmanlabs/covid-19-apis#206]
Add Coronatracker API https://api.coronatracker.com/

Tasks:

- Create Postman Collection
- Add to list

**Comment by arlemi** [comment]
@kinlane I'll take that one too.

**Comment by arlemi** [comment]
Just realised I forgot to update here... Here is the collection: 
https://documenter.getpostman.com/view/11073859/Szmcbeho?version=latest

changing to add-to-list

**Comment by kinlane** [comment]
Added to the resource directory with the latest PR - https://github.com/postmanlabs/covid-19-apis/pull/311
