### ISSUE TITLE
Wrong Link on website (https://covid-19-apis.postman.com/)

### ISSUE THREAD

**Issue by HrithikMittal** [postmanlabs/covid-19-apis#215]
The link is given to My API (COVID19 -India- API
The data is used from the official website of the Ministry of Health and Family Welfare of India.) 
For Docs is wrong Please check it and update it.
Link For my docs is mentioned below Please check and update it.https://documenter.getpostman.com/view/5665978/SzYaVdaW?version=latest

![image](https://user-images.githubusercontent.com/42075023/78294840-ab48ee00-7548-11ea-8b43-56abffd98289.png)

**Comment by tristandenyer** [comment]
I'll pick this up.

**Comment by tristandenyer** [comment]
@HrithikMittal I fixed this in PR #223 Can you verify it is correct?

**Comment by tristandenyer** [comment]
fixed
