### ISSUE TITLE
COVID-19 India statewise APIs

### ISSUE THREAD

**Issue by Salil-Jain** [postmanlabs/covid-19-apis#234]
Hi,

We, Salil Jain and Vivek Khanna(@khannavivek) have created APIs of COVID-19 cases in India.

The data provided in APIs is sourced from MOHFW India (Ministry of Health and Family Welfare) https://www.mohfw.gov.in/

Postman Documentation Link -> https://documenter.getpostman.com/view/7245444/SzYewbGb

We would be happy if you could add our APIs in the "API Collections to Help in the COVID-19 Fight" list maintained by you. https://covid-19-apis.postman.com/

Please let us know if anything else is required from our side.
We have already sent an email regarding the same.

Stay home. Stay Safe.

Regards,
Salil and Vivek

**Comment by kinlane** [comment]
Thanks for the submission, and for creating the Postman collection!!  Adding to the queue for the next build of the list.

**Comment by kinlane** [comment]
Alright, this is in the queue for https://github.com/postmanlabs/covid-19-apis/pull/259.
