### ISSUE TITLE
Covid-19 Stats API

### ISSUE THREAD

**Issue by keertyverma** [postmanlabs/covid-19-apis#237]
Hi everyone,

I have created an Node.JS + MongoDB based API with documentation at Postman. I would like to add this to Postman COVID-19 APIs resources.

Here is my Postman collection documentation https://documenter.getpostman.com/view/5352730/SzYbyxR5?version=latest

And here is my project
https://github.com/keertyverma/covid-19-stats-api.

I would love feedback on them too.

**Comment by kinlane** [comment]
Thanks for your submission!  Adding to the list for inclusion on the next build.

Thanks for creating the Postman collection!!

**Comment by keertyverma** [comment]
@kinlane Any improvement required from my end? or is the build scheduled for some time later in future?

**Comment by kinlane** [comment]
Alright, this is in the queue for https://github.com/postmanlabs/covid-19-apis/pull/259.
