### ISSUE TITLE
COVID19-India-Data-API

### ISSUE THREAD

**Issue by kinlane** [postmanlabs/covid-19-apis#241]
Create a postman collection for the following API:

- https://covid-19india-api.herokuapp.com/
- https://github.com/iSumitBanik/COVID19-India-Data-API

**Comment by arlemi** [comment]
There you go: https://documenter.getpostman.com/view/9215231/Szf25qFV?version=latest

Though the endpoint took +15s before returning a response and I'm not sure this API provides anything than the two following ones already do: 
https://documenter.getpostman.com/view/10724784/SzYXXKmA?version=latest
https://documenter.getpostman.com/view/5310017/SzYW4LYY?version=latest

We may want to reconsider adding it to the list.

**Comment by arlemi** [comment]
Well, this one must have been the easiest one to make! Love it when APIs are well documented, amazing work @iSumitBanik! 

Collection can be found here: https://documenter.getpostman.com/view/9215231/Szf25qKt?version=latest

**Comment by kinlane** [comment]
Alright, this is in the queue for https://github.com/postmanlabs/covid-19-apis/pull/259.
