### ISSUE TITLE
COVID-19 Chile stats API

### ISSUE THREAD

**Issue by sanguineti** [postmanlabs/covid-19-apis#243]
Hi!

I develop with @cmesiasd an API that brings information about coronavirus in Chile.  The data provided is sourced from the chilean government webpage [link](https://www.gob.cl/coronavirus/cifrasoficiales/).
The Postman documentation can be found [here](https://documenter.getpostman.com/view/10855464/Szf25VmX?version=latest#intro). 
The official repo of the project: [link](https://github.com/sanguineti/chile-coronapi)

Can you add this API to your "API Collections to Help in the COVID-19 Fight"  list?

Thanks in advance

**Comment by kinlane** [comment]
Alright, this is in the queue for https://github.com/postmanlabs/covid-19-apis/pull/259.
