### ISSUE TITLE
Coronavirus (COVID19) Tracker API

### ISSUE THREAD

**Issue by slotix** [postmanlabs/covid-19-apis#258]
Hello,

Please consider adding our API to the list. 
This free API tracks an actual Coronavirus (COVID-19) information about tested and infected people in multiple countries.

Examples of Live stats cards working with the API are available at https://covid-19.dataflowkit.com/
Embed Free Coronavirus (COVID-19) live statistics web widgets into your site, and your website visitor's country is determined automatically.

Internally we use [Dataflow Kit Scraper API](https://dataflowkit.com) to do that job.

Thank you.

**Comment by kinlane** [comment]
Nice looking API -- adding to our work queue for creating a Postman collection, and then we'll be able to add to the list.

**Comment by slotix** [comment]
I'm sorry, but I forgot to mention a postman collection we've already created https://documenter.getpostman.com/view/11203393/SzfAz776?version=latest

**Comment by kinlane** [comment]
Adding it to the queue for next build then!

**Comment by kinlane** [comment]
Ok, this API has been added to the latest build pull request - https://github.com/postmanlabs/covid-19-apis/pull/282 and should be published some point today.
