### ISSUE TITLE
api.covid.sh

### ISSUE THREAD

**Issue by kinlane** [postmanlabs/covid-19-apis#260]
We've launched api.covid.sh: offering COVID-19 data up to the lowest geographic classification of a country i.e. county/taluk/sub-district/district, Real-Time, Period.
We are looking forward to becoming a part of the Postman COVID-19 Efforts API Universe.

⚒️ We've built this for a developer from the ground up and hope amazing; impactful applications will be made on our free api.

🌐 We run a global edge optimized AWS Infrastructure with API latency of 100ms.

❓Who Built This?
Suhail CS (Grade 12 + https://g.co/kgs/aBPBSv) & Pranav Shikarpur( UMD Freshman + https://snpranav.com) & An Amazing Team

💰 Project Supported By Emergent Ventures of Mercatus Center (https://www.mercatus.org/)

+ refer: https://docs.covid.sh/ | https://documenter.getpostman.com/view/11046158/SzfCUmCc?version=latest

**Comment by kinlane** [comment]
Create a postman collection for the API and then add to the list.

**Comment by arlemi** [comment]
There is [an existing Postman documentation](https://documenter.getpostman.com/view/11046158/SzfCUmCc?version=latest) but as far as I can tell the endpoints aren't working anymore and the original github repository [doesn't seem to see any activity](https://github.com/covid-sh/api). 

Will close this one for now.
