### ISSUE TITLE
Canadian COVID-19 API

### ISSUE THREAD

**Issue by kinlane** [postmanlabs/covid-19-apis#262]
I run a website called COVID19Tracker.ca. We collect data in real-time throughout the day from press conferences and individual public health units to provide the most up-to-date information available on COVID-19 in Canada.

Very recently, we've developed a REST API to allow for others to access our data. We will be launching this API officially early next week (soft launch tomorrow) and wanted to be considered for inclusion in your list of COVID-19 APIs.

Here is the link to the draft API docs and API itself: api.covid19tracker.ca

Please let me know if there's anything else you'd require.

**Comment by kinlane** [comment]
Create a postman collection for this API and we can then add to the list.

**Comment by arlemi** [comment]
Here's the collection: https://documenter.getpostman.com/view/11073859/Szt5fAr3?version=latest

The `provinces` endpoint returns an error for now, guessing they'll fix it?
> ErrorException: Division by zero in file /var/www/api/app/Province.php on line 17

**Comment by kinlane** [comment]
Added to the resource directory with the latest PR - https://github.com/postmanlabs/covid-19-apis/pull/311
