### ISSUE TITLE
COVID-19 India - State and district wise

### ISSUE THREAD

**Issue by apkproz** [postmanlabs/covid-19-apis#264]
Hello,
Consider adding the API, We are collecting real-time data and publishing from Media sources.

Website using the API : [https://covidindiatracker.com/](https://covidindiatracker.com/)

API URL to access: [https://api.covidindiatracker.com/state_data.json](https://api.covidindiatracker.com/state_data.json)

API Documentation : [https://documenter.getpostman.com/view/11238297/SzfDwQdd?version=latest](https://documenter.getpostman.com/view/11238297/SzfDwQdd?version=latest)

**Comment by TestToJava** [comment]
@kinlane

**Comment by apkproz** [comment]
@kinlane

**Comment by kinlane** [comment]
Hello. I understand your impatience, but we are a handful of people spread across a bunch of projects. We spent hours getting people helping crowdsource the testing location data this week. The plan is to get back to the list of resources this week, as the resource got lots of attention right before you submitted this. Please try to be understanding of the scope of work we are doing during this hard time and not call us on Twitter when we are doing hard work.

**Comment by kinlane** [comment]
Ok, this API has been added to the latest build pull request - https://github.com/postmanlabs/covid-19-apis/pull/282 and should be published some point today.
