### ISSUE TITLE
nCov19.us API - US state, county, and zip code level API

### ISSUE THREAD

**Issue by leehanchung** [postmanlabs/covid-19-apis#265]
Hi there,

Chat with Sivcan and Kin. Sivcan suggested to raise an issue here to get our API listed.

**nCOV19.us Initiative (ncov19.us)**
ncov19.us Initiative aim to provide the most up to day country, state, and county level news and statistics and current vaccine progress information.

Postman Documentation here:
https://documenter.getpostman.com/view/10962932/SzYevF7i

API Link: 
https://api.ncov19.us

**Comment by kinlane** [comment]
Adding to the list of collections to add to listing.

**Comment by kinlane** [comment]
Ok, this API has been added to the latest build pull request - https://github.com/postmanlabs/covid-19-apis/pull/282 and should be published some point today.
