### ISSUE TITLE
COVID-19 Global Tracker with Regional Data

### ISSUE THREAD

**Issue by popofibo** [postmanlabs/covid-19-apis#291]
COVID-19 Global Tracker that drills down into states, provinces, regions across geography.

1. Realtime global counts; total cases, recovered & deceased
2. Realtime counts across countries; total cases, recovered & deceased
3. Weekly (historical) data counts; total cases, recovered & deceased
4. Drill-down of regional data for a country by states, provinces, other local regions; total cases, recovered & deceased

- Example Dashboard utilizing this data-set: https://www.cyberpurge.com/covid
- Postman collection: https://documenter.getpostman.com/view/11532614/SzzheeL7?version=latest
- API site: https://www.cyberpurge.com/covid-api

**Comment by arlemi** [comment]
Thanks for the suggestion @popofibo! The Postman collection contains an API Key, could you remove it from there and explain how to get one instead?

**Comment by popofibo** [comment]
Hi @arlemi, thanks for the feedback - I have made these suggested changes; removed API Key references from individual requests and updated documentation on how to grab one.

**Comment by arlemi** [comment]
Thanks a lot! We'll add this one on the next push to prod. 🙂
