### ISSUE TITLE
Curated COVID-19 Data and Metadata from Multiple Sources

### ISSUE THREAD

**Issue by carrrson** [postmanlabs/covid-19-apis#294]
The COVID-19 Rich Data Services API from MTNA offers curated, high-quality data and metadata from sources like Johns Hopkins, the COVID Tracking Project, Statistics Canada, and state health departments. Updated daily.

- Postman collection: https://documenter.getpostman.com/view/2220438/SzYevv9u?version=latest
- Project website: https://covid19.richdataservices.com/
- GitHub data repository: https://github.com/mtna/covid-19

**Comment by arlemi** [comment]
Thanks for sharing @carrrson ! That's an impressive API and very complete documentation, we'll add it in the next push to prod!

**Comment by kinlane** [comment]
Added to the resource directory with the latest PR - https://github.com/postmanlabs/covid-19-apis/pull/311
