### ISSUE TITLE
API & GraphQL Covid19, Source: CSSE at Johns Hopkins University

### ISSUE THREAD

**Issue by eusoumaxi** [postmanlabs/covid-19-apis#295]
## API COVID-19 and GraphQL.

This API provides data on all active, confirmed, deceased and recovered cases from covid-19.

With this API, you can have data from:

 - Clobal counts; total cases, recovered & Deaths
 - Countries 
 - States  
 - City(Usa only)

**The data comes from Johns Hopkins CSSE.**
Repo: [GIT](https://github.com/eusoumaxi/apiCovidData,)
Url: [ServerAPI](https://api-corona.azurewebsites.net/)
Documenter:  [ Documentation](https://documenter.getpostman.com/view/11787033/SzzoYuSa?version=latest#bf3f0356-c7eb-43bc-adeb-1a476e59b40c)

**Comment by arlemi** [comment]
Thanks for sharing @eusoumaxi, we'll add it to the list soon! 🙂
