### ISSUE TITLE
covidti api add to listing

### ISSUE THREAD

**Issue by jchen706** [postmanlabs/covid-19-apis#310]
I didn't have great experience with other API's, it had bad data too many times.
I made a new API accurate and refreshed more often.

The API included time-series for all US states and territories, and their respective counties and all the countries. This also has the case differential from the past day.

This API also included data scraped from Wikipedia on US states and counties.

Postman: https://explore.postman.com/api/6337/covidti-api
Website: covidti.com/api

**Comment by kinlane** [comment]
I will ad to the list for the next build. Thank you.

**Comment by kinlane** [comment]
Added to the resource directory with the latest PR - https://github.com/postmanlabs/covid-19-apis/pull/311

**Comment by kinlane** [comment]
Added to the resource directory with the latest PR - https://github.com/postmanlabs/covid-19-apis/pull/311
