### ISSUE TITLE
COVID-19 County Data

### ISSUE THREAD

**Issue by kinlane** [postmanlabs/covid-19-apis#312]
Add this API to the listing - https://covidcountydata.org/data/api#rest

A Postman collection will be needed before it can be added, but it should be pretty easy since there is an OpenAPI definition available.

Make sure to add the GraphQL too if possible!

**Comment by sglyon** [comment]
Hi @kinlane I have just created a postman collection that I've uploaded here.


I am pretty inexpreienced at creating collections for others to consume, so if there are any items here that need to be addressed before this can be added, please let me know.

- - -


Also, We do have a graphql api set up, but I haven't documented it in this collection. Would it be best to add as a separate endpoint in within the collection, or as a separate collection entirely?

Thank you


[CovidCountyData.postman_collection.json.zip](https://github.com/postmanlabs/covid-19-apis/files/5150985/CovidCountyData.postman_collection.json.zip)

**Comment by kinlane** [comment]
Thanks you for this @sglyon -- would it be possible to get URL of docs published via Postman, so in case you need to make changes, they'll be reflected. Just click on the ... action bar for your collection and publish as docs -- then paste the URL here. This will give you more control down the road!

**Comment by sglyon** [comment]
Hey @kinlane I think this is it?? 

https://documenter.getpostman.com/view/10122604/TVCe29D4

**Comment by kinlane** [comment]
That is the one. Thank you. Adding to the list for next build.

**Comment by sglyon** [comment]
Excellent, thank you!

**Comment by kinlane** [comment]
This has been added to the list of APIs in our V2 release of the COVID-19 resource center - https://postman-toolboxes.github.io/covid-19/

**Comment by sglyon** [comment]
Thanks!
