### ISSUE TITLE
Covid-19 API Tracker - DOH Philippines

### ISSUE THREAD

**Issue by Simperfy** [postmanlabs/covid-19-apis#314]
A Covid-19 API tracker that provides in-depth data from [DOH Philippines](https://www.doh.gov.ph/) that auto-updates daily.
I've search everywhere for API that provides in-depth data from DOH Philippines but found none, so I created one.

With this API, you can get data for(strictly for philippines):
- summary of covid cases
- timeline (_since the first day of reported covid case)_
- ranking of regions based on covid cases
- bed occupancy rate of hospitals
- raw data of Case/Facilities Informations (_useful for devs of machine learning_)

Project: https://github.com/Simperfy/Covid-19-API-Philippines-DOH
Documenter: https://documenter.getpostman.com/view/12463261/T1LV9jLU

If you have any questions feel free to ask me. ✋🏻

**Comment by kinlane** [comment]
This API was added with the V2 release of the COVID-19 resource center - https://postman-toolboxes.github.io/covid-19/
