### ISSUE TITLE
New Covid-19 testing sites  from excel

### ISSUE THREAD

**Issue by ankitjainpiet** [postmanlabs/covid-19-apis#315]
I would request you to add https://sheetlabs.com/NCOR/covidtestcentersinUS this api in the postman for covid test centers in US.

**Comment by arlemi** [comment]
Thanks for the suggestion @ankitjainpiet , can you please create a Postman collection and publish it as documentation so we can add it to the page? 
More info around that here https://learning.postman.com/docs/publishing-your-api/publishing-your-docs/

**Comment by ankitjainpiet** [comment]
https://documenter.getpostman.com/view/11672223/TVCfV7fX i created this

**Comment by kinlane** [comment]
We've added this collection to our latest V2 release of the CCOVID-19 resource center - https://postman-toolboxes.github.io/covid-19/

Thanks for the submission!
