### ISSUE TITLE
Wrong documentation links

### ISSUE THREAD

**Issue by antklim** [postmanlabs/covid-19-apis#316]
Documentation for `COVID-19 testing locations in Australia` and `US Energy Information Administration` reference to the `COVID-19 Japan Web API`.

Wrong link for `COVID-19 testing locations in Australia` - https://github.com/postmanlabs/covid-19-apis/blob/develop/src/components/Microsite/Collections/Collection.data.json#L167
Wrong link for `US Energy Information Administration` - https://github.com/postmanlabs/covid-19-apis/blob/develop/src/components/Microsite/Collections/Collection.data.json#L173

**Comment by kinlane** [comment]
These got fixed in V2 release - https://postman-toolboxes.github.io/covid-19/ -- Thanks for reporting!!!
