### ISSUE TITLE
Global Coronavirus API

### ISSUE THREAD

**Issue by 0xnu** [postmanlabs/covid-19-apis#317]
Please see the API Documentation here: https://www.covid19api.dev/

Additionally, we have published two wrappers:

JavaScript: https://github.com/Cloudeya/coronavirusapi-wrapper
Go: https://github.com/Cloudeya/coronavirusapi-go

**Comment by kinlane** [comment]
Excellent! We have added it to version 2.0 of the resource center as a featured collection - https://postman-toolboxes.github.io/covid-19/
