### ISSUE TITLE
API Error | Covid-19

### ISSUE THREAD

**Issue by JayanthanSivaloganthan** [postmanlabs/covid-19-apis#318]
Hi ,

We have been using below given API for a couple of months.
https://api.covid19api.com/all

We are getting the below error from last week. Could you please advise on this issue?

DataSource.Error: Unable to read data from the transport connection: The connection was closed.

Jayanthan

**Comment by DannyDainton** [comment]
Hey @JayanthanSivaloganthan 

I think this issue would be better handled by the folks who created the API.

https://covid19api.com/
