### ISSUE TITLE
API Suggestion: US Energy Data

### ISSUE THREAD

**Issue by kinlane** [postmanlabs/covid-19-apis#70]
This was an API suggestion via email: 

> The U.S. Energy Information Administration has a robust API available, providing insight about all things energy-related.
> 
> Some live feeds are available on their website, but people who are interested in how human behavior is changing in response to COVID-19 may be interested to review some of the electricity sales data or transportation fuels related data.
> 
> https://www.eia.gov/opendata/qb.php?category=1002 
> 

**Next Steps:**

- Create a Postman Collection for the API.
- Publish collection as template
- List API as COVID-19 resources

**Comment by stcalica** [comment]
@kinlane  I can also take this one on, as I have friends who have a company whose sole purpose is creating Dashboards for Dept Energy using all their APIs. Feel free to shoot this to me as well.

**Comment by arlemi** [comment]
@stcalica Are you still working on that one?

**Comment by stcalica** [comment]
The API here is not nicely organized by endpoint.
There are literally just two endpoints: category and series. The category and series wanted is denoted by ID number. 

There are over 100,000+ categories and series according to EIA. And it seems that way when I explore their API browse. 
My solution is to possibly try to use the visualizer to make a category and series explorer. 
Then have two endpoints they can use to plug and play with. 

Or is there any other suggestions to tackle this? 
@kinlane  @arlemi

**Comment by stcalica** [comment]
Published a Postman Collection here: 
https://documenter.getpostman.com/view/1034536/Szme4dco?version=latest

this one is a bit different cause it's data source is so large and it's really just two GET requests for Categories and Series. I tried to add value by creating a visualizer to explore the categories and series to easily expose the IDs.
