### ISSUE TITLE
Data API for Indian States

### ISSUE THREAD

**Issue by shaharyar-shamshi** [postmanlabs/covid-19-apis#75]
I have created the API  to get Data for Indian States which include the Total Cases statewise , Total Recovery and Total death and hosted it on the Heroku how should I include that in this project to make it publicly available as I can't find any contribution doc

**Comment by kinlane** [comment]
This is the correct first step -- submitting a GitHub issue. Next I recommend creating a postman collection for your API and publish as a Postman template (available on the arrow for your collection > Publish Docs). 

Try to make sure you have documented each individual request as well as the overall collection with as much background and other relevant links to help developers understand what the API is all about.

Once you've published as a template, post the link to the documentation / collection here, and we will add to the master list and update with the next website update. 

If you have any questions you can leave them here and we'll work to answer them.
