### ISSUE TITLE
Google Sheets to API

### ISSUE THREAD

**Issue by adomhamza** [postmanlabs/covid-19-apis#77]
I am in need of assistance in publishing data from a Google Sheet as an API so that it can be more accessible across many different applications. 
Thank you.

**Comment by kinlane** [comment]
Can you provide more detail on your project, data source, etc. so that we can prioritize with other projects? Then we can consider adding it to the list of projects for the team and community to work on.

**Comment by suensummit** [comment]
I'm not sure whether it's the case but might be an example: [Summarized data in Taiwan].(https://docs.google.com/spreadsheets/d/e/2PACX-1vRM7gTCUvuCqR3zdcLGccuGLv1s7dpDcQ-MeH_AZxnCXtW4iqVmEzUnDSKR7o8OiMLPMelEpxE7Pi4Q/pubhtml#)
