### ISSUE TITLE
Official API for ECDC world wide cases - daily updates

### ISSUE THREAD

**Issue by Craphtex** [postmanlabs/covid-19-apis#78]
## Description
From ECDC webpage [[1](https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide)]:
> The downloadable data file is updated daily and contains the latest available public data on COVID-19. Public-use data files allows users to manipulate the data in a format appropriate for their analyses. Users of ECDC public-use data files must comply with data use restrictions to ensure that the information will be used solely for statistical analysis or reporting purposes.

## Link format
`https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide-YYYY-MM-DD.csv`*

*Please note that `YYYY-MM-DD` need to be replaced with the desired date.
- Example for 2020-03-26:
https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide-2020-03-26.csv

## See also
ECDC COVID-19 main page: https://www.ecdc.europa.eu/en/novel-coronavirus-china

## Source
[1] https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide

**Comment by kinlane** [comment]
Great! Thank you. I will add to the list to create a Postman collection for. Once there is a collection that makes it something users can run manually or automate it, we'll add to the list of resources.

We'll be prioritizing projects and accomplishing the work internally or based upon community assistance.

**Comment by arlemi** [comment]
Link to collection: https://documenter.getpostman.com/view/11073859/Szt5equ9?version=latest

**Comment by kinlane** [comment]
Added to the resource directory with the latest PR - https://github.com/postmanlabs/covid-19-apis/pull/311
