### ISSUE TITLE
Not able to import US Digital Registry API and NovelCOVID API collections

### ISSUE THREAD

**Issue by vvs11** [postmanlabs/covid-19-apis#80]
I tried importing collections on the website. Not able to import the two collections mentioned above. Getting this error:
"We can't seem to find the collection you're trying to import."

**Comment by tristandenyer** [comment]
@kinlane @ch264 Looks like we are missing the collection ID on Run in Postman buttons for:
— US Digital Registry API (URL has placeholder brackets: https://app.getpostman.com/run-collection/[data-postman-var-1])
— NovelCOVID API (400 page)

**Comment by ch264** [comment]
I am looking into it

**Comment by kinlane** [comment]
The NovelCOVID API just has an extra c on the end of the GUID.

**Comment by kinlane** [comment]
The US Digital service id is wrong -- should be: 8854915-6dc5390c-0f79-4295-a38f-61fa3ec00460-SzS7NkEm

**Comment by ch264** [comment]
PR is already in
