### ISSUE TITLE
novelcovid depretated by V2 endpoints

### ISSUE THREAD

**Issue by gottfriedsz** [postmanlabs/covid-19-apis#82]
Some of the endpoints of https://github.com/novelcovid/api have been deprecated by V2.

https://documenter.getpostman.com/view/8854915/SzS7R6uu?version=latest

**Comment by ch264** [comment]
@kinlane ^

**Comment by kinlane** [comment]
Adding to the list of collection to rework.

**Comment by kinlane** [comment]
being deal with as part of [I own NovelCOVID API](https://github.com/postmanlabs/covid-19-apis/issues/84)
