### ISSUE TITLE
I own NovelCOVID API.

### ISSUE THREAD

**Issue by EliteDaMyth** [postmanlabs/covid-19-apis#84]
I own the https://GitHub.com/NovelCOVID/API I just saw it was in postman api's. I do not mind this but the documentation is a little outdated. If possible please update according to readme. Thanks!
You can contact me through discord if needed. EliteDaMyth#0690

**Comment by prashantdawar** [comment]
Hi.
I can voluntary provide you scrapping data from 500 pages by writing custom crawler for each page crawling in cyclic manner.

Let me know

**Comment by kinlane** [comment]
Hello! Thanks for pinging us. I will add it to our list to update. Happy to update the link to a Postman collection you published and owned, then you could control content.

**Comment by EliteDaMyth** [comment]
the docs are very very outdated! https://corona.lmao.ninja/docs is swagger generated which is up to date at all times. if you can update it i would be grateful!

**Comment by EliteDaMyth** [comment]
@kinlane

**Comment by arlemi** [comment]
@EliteDaMyth I've made a first update to switch to the v2 endpoints, I'll add the new endpoints now. If you'd like to own the collection let me know, we're happy to transfer it to you so you can update without having to go through us! :D

**Comment by arlemi** [comment]
Continuing the discussion there https://github.com/NovelCOVID/API/issues/534

**Comment by EliteDaMyth** [comment]
> Continuing the discussion there [NovelCOVID/API#534](https://github.com/NovelCOVID/API/issues/534)

closing it here :)
