### ISSUE TITLE
Create Collection for COVID-19 Finnhub API

### ISSUE THREAD

**Issue by kinlane** [postmanlabs/covid-19-apis#90]
From email:

Just wanted to suggest an api for covid-19. Finnhub - https://finnhub.io/docs/api#covid-19 - enables you to get real-time updates on the number of COVID-19 (Corona virus) cases in the US with a state-by-state breakdown. Data is sourced from CDC and reputable sources.

Tasks: 

- Create Postman Collection
- Add to resource listing

**Comment by ProBeta1** [comment]
Collection created : https://documenter.getpostman.com/view/10724784/SzYW3LFa

**Comment by ProBeta1** [comment]
https://github.com/postmanlabs/covid-19-apis/pull/99

**Comment by kinlane** [comment]
Ok this has been included in #122 and upon review it will be merged.
