### ISSUE TITLE
Create Postman Collection for Philippines Coronavirus API

### ISSUE THREAD

**Issue by kinlane** [postmanlabs/covid-19-apis#91]
From Email:

I've developed a API for tracking the coronavirus disease in the Philippines.

Here's the repo https://github.com/sorxrob/coronavirus-ph-api.

Here's the docs https://coronavirus-ph-api.now.sh/

Tasks:

- Create Postman Collection
- Add to resource listing

**Comment by sorxrob** [comment]
Hello, thanks! Here's the collection https://documenter.getpostman.com/view/4314981/SzYW2fbH

**Comment by kinlane** [comment]
Awesome!! Adding to our list of resources.

**Comment by ProBeta1** [comment]
https://github.com/postmanlabs/covid-19-apis/pull/99

**Comment by kinlane** [comment]
Ok this has been included in #122 and upon review it will be merged.
