### ISSUE TITLE
Create Postman Collection for Elsevier API

### ISSUE THREAD

**Issue by kinlane** [postmanlabs/covid-19-apis#92]
From email: 

_We can offer a research dataset search engine API (indexing datasets from 60+ scientific data repositories worldwide), to include in your collection of COVID-19 API resources at https://covid-19-apis.postman.com/. 

 - [Example Query](https://api.datasearch.elsevier.com/api/v2/search?query=%22COVID-19%22%20OR%20Coronavirus%20OR%20%22Corona%20virus%22%20OR%20%222019-nCoV%22%20OR%20%22SARS-CoV%22%20OR%20%22MERS-CoV%22%20OR%20%22Severe%20Acute%20Respiratory%20Syndrome%22%20OR%20%22Middle%20East%20Respiratory%20Syndrome%22)&requester=DS&pageSize=10&page=0&debug=false&cmShowFields=false)

- [API Docs](https://datasearch.elsevier.com/api/docs#/search/search_1)

As you can see, 3410 datasets are available so far.  We'd be delighted to be included. Please let us know any queries or any more information we can send._ 

Tasks:

- Import Swagger and create Postman collecitoin
- Add to the list of resources.

**Comment by ProBeta1** [comment]
Done , PR underway.

**Comment by kinlane** [comment]
Ok this has been included in #122 and upon review it will be merged.
