### ISSUE TITLE
Generate Postman Collections for Department of Veteran Affairs API resources

### ISSUE THREAD

**Issue by kinlane** [postmanlabs/covid-19-apis#94]
From Email:

While we’re furiously adding COVID specific content to our API catalog, some of these may be of use today as they enable Veterans and their support network the to do things remotely instead of visiting a VA facility, all documented at https://developer.va.gov

- Benefits Intake API – These allow veterans (or people acting on their behalf) the ability to submit benefits claims remotely.
- Claims API (equivalent to Benefits Intake, but instead of digitized PDF’s, just data and only for disability claims at the moment)
- Forms API -  allows veterans to get the latest forms to submit to VA
- Facilities API – hopefully obvious.  Likely to be adding timely, COVID-19 specific content to this very soon
- Veterans Health History API – Allows veterans to receive their VA health history on the iPhone, Android devices, and desktop apps
- Veteran Verification API – Allows a person to be confirmed as having veteran status without having to product physical documentation (DD-214, etc).

Tasks:

- Convert all of the VA OpenAPI definitions into Postman Collections
- Add to our list of resources.

**Comment by stcalica** [comment]
@kinlane  feel free to assign this one over to me!

**Comment by stcalica** [comment]
blocked due to OpenID is not a supported feature and it is the method the VA uses to authenticate. Unblocking by letting users know they will have to grab their own access token by possibly using the sample app the VA provides. 

API is broken down currently. Adding documentation and making it more user friendly with scripts and etc.

**Comment by kinlane** [comment]
Thanks for looking into. I'll review when I have time and talk to the VA folks about the friction. Appreciate you carving  out time.

**Comment by stcalica** [comment]
I figured it out now. Had to change their sample node apps to give me a bearer token. 
Also opened a few issues to make it easier. 

I left you a slack message too.

**Comment by stcalica** [comment]
https://documenter.getpostman.com/view/1034536/SzfCV6TH?version=latest 

Here is the Postman Collection.

**Comment by stcalica** [comment]
@ch264  pull request above. please review :)
