### ISSUE TITLE
get state data from API 

### ISSUE THREAD

**Issue by ch264** [postmanlabs/covid-19-apis#96]
-  right now we are turning json data into gatsbe nodes and query them with graphql
- hook up API endpoints to update data

**Comment by kinlane** [comment]
California: https://covid-19-testing.github.io/locations/california/complete.json
Washington - https://covid-19-testing.github.io/locations/washington/complete.json
New York - https://covid-19-testing.github.io/locations/new-york/complete.json
Massachusetts - https://covid-19-testing.github.io/locations/massachusetts/complete.json

**Comment by ch264** [comment]
Rest API is not in the app. 
I will keep this ticket open so that we can log the  available endpoints
